image:
  repository: davis88/sampleapp
  tag: v2
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

version: v1

deployment:
  containerPort: 3000

param:
  appkey: 5afsfds4e39b72273c3d003141
  defaultCity: ""

gatewayhostname: "jp.x.x.x.x.nip.io"
gatewayport: 80


replicaCount: 1
productionEnv: false
productionReplicaCount: 2


